version: '2'
services:
  server:
    build: .
    container_name: zelig-container
    ports:
     - "8081:8081"
    volumes:
     - .:/app
    environment:
     - TARGET_SERVER_BASE_URL=http://172.17.0.1:8000
     - ZELIG_HOST=0.0.0.0
     - ZELIG_PORT=8081
     - ZELIG_MODE=observer
