from urllib.parse import urlparse
import os

from zelig.constants import RequestMatchCriteria, ZeligMode, ResponseMatchCriteria, FILES_DIRECTORY
from .properties import Property, IntProperty, MultiEnumProperty, PathProperty, AutoGeneratedDirectoryProperty

DEFAULT_REQUEST_MATCH_ON = ' '.join((cr.value for cr in RequestMatchCriteria))
DEFAULT_RESPONSE_MATCH_ON = ' '.join((cr.value for cr in ResponseMatchCriteria))


class BaseConfig:
    mode = None
    base_files_dir = PathProperty(FILES_DIRECTORY)
    cassette_directory_name = AutoGeneratedDirectoryProperty('ZELIG_CASSETTE_DIRECTORY', prefix='cassette')
    target_server_base_url = Property('TARGET_SERVER_BASE_URL')

    def __init__(self):
        self.__perform_check()

    @property
    def target_server_host(self):
        res = urlparse(self.target_server_base_url).netloc
        return res

    @property
    def cassette_directory(self):
        return os.path.join(self.base_files_dir, self.cassette_directory_name)

    def __perform_check(self):
        for k in dir(self):
            if not k.startswith('__'):
                getattr(self, k)


class PlaybackConfig(BaseConfig):
    mode = ZeligMode.PLAYBACK
    request_match_on = MultiEnumProperty('REQUEST_MATCH_ON', enum_class=RequestMatchCriteria,
                                         default=DEFAULT_REQUEST_MATCH_ON)
    response_match_on = MultiEnumProperty('RESPONSE_MATCH_ON', enum_class=ResponseMatchCriteria,
                                          default=DEFAULT_RESPONSE_MATCH_ON)

    playback_report_directory_name = AutoGeneratedDirectoryProperty('ZELIG_PLAYBACK_REPORT_DIRECTORY',
                                                                    prefix='playback_report')

    @property
    def playback_report_directory(self):
        return os.path.join(self.base_files_dir, self.playback_report_directory_name)


class RecordConfig(BaseConfig):
    mode = ZeligMode.RECORD
    zelig_host = Property('ZELIG_HOST', default='0.0.0.0')
    zelig_port = IntProperty('ZELIG_PORT', default=8081)

    request_match_on = MultiEnumProperty('REQUEST_MATCH_ON', enum_class=RequestMatchCriteria,
                                         default=DEFAULT_REQUEST_MATCH_ON)


class ServeConfig(BaseConfig):
    mode = ZeligMode.SERVE
    zelig_host = Property('ZELIG_HOST', default='0.0.0.0')
    zelig_port = IntProperty('ZELIG_PORT', default=8081)
    request_match_on = MultiEnumProperty('REQUEST_MATCH_ON', enum_class=RequestMatchCriteria,
                                         default=DEFAULT_REQUEST_MATCH_ON)


class ObserveConfig(BaseConfig):
    mode = ZeligMode.OBSERVE
    zelig_host = Property('ZELIG_HOST', default='0.0.0.0')
    zelig_port = IntProperty('ZELIG_PORT', default=8081)

    request_match_on = MultiEnumProperty('REQUEST_MATCH_ON', enum_class=RequestMatchCriteria,
                                         default=DEFAULT_REQUEST_MATCH_ON)

    response_match_on = MultiEnumProperty('RESPONSE_MATCH_ON', enum_class=ResponseMatchCriteria,
                                          default=DEFAULT_RESPONSE_MATCH_ON)
    observe_report_directory_name = AutoGeneratedDirectoryProperty('ZELIG_OBSERVE_REPORT_DIRECTORY',
                                                                   prefix='observe_report')

    @property
    def observe_report_directory(self):
        return os.path.join(self.base_files_dir, self.observe_report_directory_name)
